name: Migrate DB

on:
  push:
    branches: [main]
    paths: ['supabase/migrations/**']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: migrate-db
  cancel-in-progress: false

jobs:
  migrate:
    name: Push Migrations
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release')"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51 # v1.6.0
        with:
          version: latest

      - run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
